---
# vim: set ft=ansible:
#
#  This role deletes specified container image through the atomic images
#    delete command
#
- name: Fail if image is undefined
  fail:
    msg: "Image is undefined"
  when: image is undefined

- name: Remove specified image
  command: atomic --debug --assumeyes images delete {{ image }}
